# Generated by Django 2.2.4 on 2022-06-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_confirem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
